### ISSUE TITLE
list of minor issues

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#152]
# Today

## Adrian
- [x] Remove Rendering Vignette
- [x] Remove Table Pagination
- [x] Viewer

## Gabe
- [x]  `value_at(tbl, c("AGE", "mean"), "ARM A")`
            - this needs to throw an error and reference to cell_values if paths are not complete > to leafs 
            - [ ] add usage to `value_at`
- [x] `tail` warning (in R >4)
   ![image](https://user-images.githubusercontent.com/7786462/102015495-45aa3400-3d5c-11eb-84b1-e1c32df4d024.png)
- [x] print method for `RowsVerticalSection`

# Tasks For Backlog

- `simple_analysis` only returns the `mean` for continuous variables, should we add `range`, `median`, `sd`, etc?
    - next release

- [x] examples in `analyze_colvars` & `split_cols_by_multivar` gives a weird table
   - rcell used instead of inrows, ADRIAN fixes it
  
- add meaningful example for `split_cols_by_cutfun` and `split_rows_by_cutfun`

-  in `add_overall_level` examples, how do we compound the split functions (with `drop_split_levels`)
            - next release
          
- `add_overall_col` should we deprecate? 

 
- add example for `reorder_split_levels` and `trim_levels_in_group`

- [x]  address in tests
   ![image](https://user-images.githubusercontent.com/7786462/102220216-cd20b000-3ee0-11eb-840d-be8a24fd1f15.png)

    ```
    docker run -ti rocker/tidyverse:4.0.1 /bin/bash
    git clone -b gabe_tabletree_work https://github.com/Roche/rtables.git
    R CMD build --no-build-vignettes rtables
    R CMD check --no-manuals --no-vignettes rtables_*
   ```
   clone rtables, test...

* Remove?
  - `rbindl_rtables` -- seams to be needed by `rbind`
  - `rbind2`  -- is used in isert_row
  - [x] `rtabulate`, `by_all`, `by_add_total`, `by_quartile`
  - [ ] `rrowl`
  - [x] `header_add_N`
  - [x] `header<-` & `header`
  -  `insert_rrow` -- is needed
  - `indent` is needed by `isert_rrow`
  - `list_wrap_x` -- needed
  - [x] `label`
  - [x] `indented_row.names`

# Discussion Points

- [x] add a print invocation in tests

- [x] table_structure <- function(x, expand = TRUE) {
- [x] examples setMethod("[<-", c("VTableTree", val

**Comment by gmbecker** [comment]
> * [ ]  `tail` warning (in R >4)
>   ![image](https://user-images.githubusercontent.com/7786462/102015495-45aa3400-3d5c-11eb-84b1-e1c32df4d024.png)
> * [ ]  `simple_analysis` only returns the `mean` for continuous variables, should we add `range`, `median`, `sd`, etc?
I'm not sure the default analysis function should generate ~5 rows per leaf without being asked to...


> * [ ]  examples in `analyze_colvars` & `split_cols_by_multivar` gives a weird table
> * [ ]  add meaningful example for `split_cols_by_cutfun` and `split_rows_by_cutfun`
> * [ ]  in `add_overall_level` examples, how do we coumound the split functions (with `drop_split_levels`)

Currently the only way to do this is understand the system well enough to write a new split function.  Having a nice api for that is on the list of things to do but certainly not by tomorrow.

> * [ ]  `add_overall_col` should we deprecate?

The primary use for this, which is happening in practice, is to relabel the default column when no column splitting is happening. Though technically it could also be used to add a overall column as the last column in the table, if called after `split_cols_by` (etc). So we can't deprecate it without some extra work happening first.

> * [ ]  add example for `reorder_split_levels` and `trim_levels_in_group`
> * [ ]  look at `[` examples
>   - does the `value` argument work as intended?

There was some bugginess there that I have fixed but I'm not sure what you mean. See the new tests in `tests/testthat/test-subset-access.R` so at least single cell and cells across one row now work ok.

> * [ ]  add example to `as.vector`

The only reason as.vector is even in there is because something is using it as a hold-over from when it made sense. People should be calling `cell_values`, not `as.vector` so I don't think it needs an example, personally.

> * [ ]  delete file `tests/testthat/test-col_by.R`
> 
> * Remove?
>   
>   * [ ]  `rbindl_rtables`
>   * [ ]  `rbind2`
>   * [ ]  `rtabulate`, `by_all`, `by_add_total`, `by_quartile`, `indent`
>   * [ ]  `rrowl`
>   * [ ]  `header_add_N`
>   * [ ]  `header<-`
>   * [ ]  `insert_rrow`
>   * [ ]  `list_wrap_x`
>   * [ ]  `label`
>   * [ ]  `indented_row.names`
> * Vignettes
>   
>   * tabuleation concepts
>     
>     * [ ]  Pattern III

**Comment by waddella** [comment]
I will close this issue and create a new one with the deltas
